export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const BOOKS_LOADING = 'BOOKS_LOADING';
export const BOOKS_LOADING_FAILED = 'BOOKS_LOADING_FAILED';
export const BOOKS_LOADED = 'BOOKS_LOADED';

export const ADD_TO_CART = 'ADD_TO_CART';
export const SUBTRACT_FROM_CART = 'SUBTRACT_FROM_CART';

export const FETCH_CART = 'FETCH_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const ADD_QTY = 'ADD_QTY';
export const SUBTRACT_QTY = 'SUBTRACT_QTY';
